//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.ComponentModel;
using UnityEngine;
using UnityEngine.EventSystems;

namespace revisual.pipit
{
    public interface ICoroutineHandler
    {
        Coroutine StartCoroutine(string methodName);
        Coroutine StartCoroutine(IEnumerator routine);
        Coroutine StartCoroutine(string methodName, [DefaultValue("null")] object value);
        Coroutine StartCoroutine_Auto(IEnumerator routine);
        void StopAllCoroutines();
        void StopCoroutine(Coroutine routine);
        void StopCoroutine(IEnumerator routine);
        void StopCoroutine(string methodName);
    }

    interface ICustomEvent : IEventSystemHandler
    {
        void Message(string val);
    }
}

