//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;

namespace revisual.pipit
{
    using data;
    public class BookDecoder
    {
        private JSONObject json;
        private Book book;

        public BookDecoder(string text)
        {
            json = new JSONObject(text);
        }

        public Book Decode()
        {
            JSONObject imageList = json.GetField("book").GetField("imageURLs");

            book = new Book(imageList.Count);
            book.id = json.GetField("book").GetField("id").str;
           

            imageList.list.ForEach(x =>
            {
                book.Add(x.str);                
            });


            return book;
        }

        private void decodeImages()
        {
            
        }


    }


}