//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;

namespace revisual.pipit.data
{
    using data;
    public class ProjectListDecoder
    {
        private JSONObject _json;
        private ProjectType _type;


        public ProjectListDecoder(string text, ProjectType type)
        {
            _json = new JSONObject(text);
            _type = type;
        }

        public ProjectList Decode()
        {
           
            JSONObject itemList = 
                (_type.Equals(ProjectType.LIST))
                ? _json.GetField("projects")
                : _json.GetField("project").GetField("content");

            ProjectList projectList = new ProjectList(itemList.Count);

            itemList.list.ForEach(x =>
            {
                ProjectItem item =  projectList.Add(x.GetField("id").str);
                item.title = x.GetField("title").str;
                item.description = x.GetField("descr").str;
                item.thumbnailURL = x.GetField("thumb").str;
                //item.priority = (uint)x.GetField("priority").f;
                item.type = _type;
            });


            return projectList;
        }
    }


}